### ISSUE TITLE
请教一下如何解决本地启动运行报错

### ISSUE THREAD

**Issue by iarthit** [TMaize/tmaize-blog#35]
我执行下面这条命令报错
```
bundle exec jekyll serve --watch --host=127.0.0.1 --port=8080
```
```
<internal:D:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- rexml/parsers/baseparser (LoadError)
        from <internal:D:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/kramdown-1.17.0/lib/kramdown/parser/html.rb:10:in `<top (required)>'
        from <internal:D:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:D:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown/html.rb:10:in `<top (required)>'
        from <internal:D:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:D:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown/paragraph.rb:14:in `<top (required)>'
        from <internal:D:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:D:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:345:in `<class:Kramdown>'
        from D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:60:in `<module:Parser>'
        from D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:19:in `<module:Kramdown>'
        from D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:17:in `<top (required)>'
        from <internal:D:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:D:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-3.8.5/lib/jekyll/converters/smartypants.rb:3:in `<top (required)>'
        from <internal:D:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:D:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-3.8.5/lib/jekyll.rb:13:in `block in require_all'
        from D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-3.8.5/lib/jekyll.rb:12:in `each'
        from D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-3.8.5/lib/jekyll.rb:12:in `require_all'
        from D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-3.8.5/lib/jekyll.rb:194:in `<top (required)>'
        from <internal:D:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:D:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-3.8.5/exe/jekyll:8:in `<top (required)>'
        from D:/Ruby32-x64/bin/jekyll:25:in `load'
        from D:/Ruby32-x64/bin/jekyll:25:in `<main>'
```

我安装了ruby 环境和依赖，使用vscode

**Comment by iarthit** [comment]
知道原因了，把ruby版本降到3以下就行了

**Comment by diaowinner** [comment]
或者把 Jekyll 更新一下：
https://github.com/TMaize/tmaize-blog/issues/38#issuecomment-2192005517
