### ISSUE TITLE
cloudflare page 部署失败

### ISSUE THREAD

**Issue by teg1c** [TMaize/tmaize-blog#38]
我准备把您这个部署在 cloudflare pages ，部署过程中提示
```

11:17:37.285 | Executing user command: jekyll build
-- | --
11:17:38.487 | /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/runtime.rb:304:in `check_for_activated_spec!': You have already activated i18n 1.14.1, but your Gemfile requires i18n 0.9.5. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)


11:17:37.285 | Executing user command: jekyll build
-- | --
11:17:38.487 | /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/runtime.rb:304:in `check_for_activated_spec!': You have already activated i18n 1.14.1, but your Gemfile requires i18n 0.9.5. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)


11:17:37.285 | Executing user command: jekyll build
-- | --
11:17:38.487 | /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/runtime.rb:304:in `check_for_activated_spec!': You have already activated i18n 1.14.1, but your Gemfile requires i18n 0.9.5. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)



```

**Comment by diaowinner** [comment]
我把 build command 调成 `bundle install; bundle exec jekyll build`，但是出现这样的错误了：
```
23:29:23.833 | <internal:/opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- rexml/parsers/baseparser (LoadError)
23:29:23.833 | from <internal:/opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
23:29:23.833 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kramdown-1.17.0/lib/kramdown/parser/html.rb:10:in `<top (required)>'
23:29:23.833 | from <internal:/opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
23:29:23.834 | from <internal:/opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
23:29:23.834 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown/html.rb:10:in `<top (required)>'
23:29:23.834 | from <internal:/opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
23:29:23.834 | from <internal:/opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
23:29:23.834 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown/paragraph.rb:14:in `<top (required)>'
23:29:23.834 | from <internal:/opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
23:29:23.834 | from <internal:/opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
23:29:23.834 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:345:in `<class:Kramdown>'
23:29:23.834 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:60:in `<module:Parser>'
23:29:23.834 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:19:in `<module:Kramdown>'
23:29:23.835 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:17:in `<top (required)>'
23:29:23.835 | from <internal:/opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
23:29:23.835 | from <internal:/opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
23:29:23.835 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/jekyll-3.8.5/lib/jekyll/converters/smartypants.rb:3:in `<top (required)>'
23:29:23.835 | from <internal:/opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
23:29:23.835 | from <internal:/opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
23:29:23.835 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/jekyll-3.8.5/lib/jekyll.rb:13:in `block in require_all'
23:29:23.835 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/jekyll-3.8.5/lib/jekyll.rb:12:in `each'
23:29:23.835 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/jekyll-3.8.5/lib/jekyll.rb:12:in `require_all'
23:29:23.835 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/jekyll-3.8.5/lib/jekyll.rb:194:in `<top (required)>'
23:29:23.835 | from <internal:/opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
23:29:23.835 | from <internal:/opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
23:29:23.835 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/jekyll-3.8.5/exe/jekyll:8:in `<top (required)>'
23:29:23.836 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/bin/jekyll:25:in `load'
23:29:23.836 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/bin/jekyll:25:in `<top (required)>'
23:29:23.836 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
23:29:23.836 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
23:29:23.836 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
23:29:23.836 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/cli.rb:492:in `exec'
23:29:23.836 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
23:29:23.836 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
23:29:23.836 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
23:29:23.836 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
23:29:23.836 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
23:29:23.837 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
23:29:23.837 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:45:in `block in <top (required)>'
23:29:23.837 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
23:29:23.837 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:33:in `<top (required)>'
23:29:23.839 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/bin/bundle:25:in `load'
23:29:23.840 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/bin/bundle:25:in `<main>'
23:29:23.842 | Failed: Error while executing user command. Exited with error code: 1
23:29:23.851 | Failed: build command exited with code: 1
23:29:24.784 | Failed: error occurred while running build command
```
